site_name: SeniAura - Documentation Technique
site_description: Documentation technique pour le dashboard de santé CardiAURA / SeniAura.
site_author: Raphael

theme:
  name: material
  custom_dir: overrides
  language: fr
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passage en mode sombre
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passage en mode clair
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Vue d'ensemble: index.md
  - Arborescence: structure.md
  - Données: data.md
  - Architecture & Flux: backend.md
  - Pages & Logique: pages.md
  - Assets Front-end: frontend.md
  - Déploiement & FAQ: ops.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
